listener 8883
protocol websockets
cafile ./config/certs/rootCA.pem
certfile ./config/certs/localcerts.pem
keyfile ./config/certs/localcerts-key.pem
allow_anonymous true
listener 8333
protocol websockets
cafile ./config/certs/rootCA.pem
certfile ./config/certs/localcerts.pem
keyfile ./config/certs/localcerts-key.pem
allow_anonymous true
listener 8083
protocol websockets
cafile ./config/certs/rootCA.pem
certfile ./config/certs/localcerts.pem
keyfile ./config/certs/localcerts-key.pem
allow_anonymous true
log_type all
