listener 8883
protocol websockets
cafile /home/tsusaka/.local/share/mkcert/rootCA.pem
certfile ../certificates/localhost.pem
keyfile ../certificates/localhost-key.pem
allow_anonymous true
listener 8333
protocol websockets
cafile /home/tsusaka/.local/share/mkcert/rootCA.pem
certfile ../certificates/localhost.pem
keyfile ../certificates/localhost-key.pem
allow_anonymous true
listener 8083
protocol websockets
cafile /home/tsusaka/.local/share/mkcert/rootCA.pem
certfile ../certificates/localhost.pem
keyfile ../certificates/localhost-key.pem
allow_anonymous true
log_type all